baseURL = "https://blog.simonrw.com"
languageCode = "en-us"
title = "Circularspace"
theme = "anubis"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true

[menu]

  [[menu.main]]
  identifier = "archive"
  name = "Archive"
  title = "Archive"
  url = "/posts/"
  weight = 0.0

