[build]
publish = "public"
command = "hugo --gc --minify"

[content.production.environment]
HUGO_VERSION = "0.68.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GIMME_GO_VERSION = "1.14.1"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.68.3"
GIMME_GO_VERSION = "1.14.1"
HUGO_ENV = "production"
